config/routes.rb
Rails.application.routes.draw do
  resources :videos
  root to: 'videos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
# frozen_string_literal: true

class Video < ApplicationRecord
  mount_uploader :attachment, VideoUploader

  def set_success(format, opts)
    self.success = true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  before_action :find_video, only: %i[show edit update destroy]

  def index
    @videos = Video.all
  end

  def show; end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)
    if @video.save
      flash[:success] = 'Видео обрабатывается 30сек!'
      ConverterWorker.perform_async(@video.id)
      redirect_to video_path(@video)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @video.update(video_params)
      ::ConverterWorker.perform_async(@video.id)
      redirect_to :show
    else
      render :edit
    end
  end

  def destroy
    @video.destroy
    redirect_to videos_path
  end

  private

  def find_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav_bar.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  = image_tag 'camera.png', class: 'navbar-brand camera'
  button.navbar-toggler aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarNavAltMarkup" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      = link_to 'Home', videos_path, class: 'nav-item nav-link'
      = link_to 'New', new_video_path, class: 'nav-item nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title VideoConverter
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body

    = render 'layouts/nav_bar'
    span.box_flash.mt-5
      p.flash_success = flash[:success]
    = yield

app/views/videos/_form.html.slim
.container-form
  = form_for @video do |f|
    = f.file_field :attachment, class: 'form-control', required: true
    = f.button 'Сохранить', class: 'btn btn-primary form-control mt-2'

app/views/videos/edit.html.slim
= render 'form'

app/views/videos/index.html.slim
.container
  .content.mt-5
    - @videos.each do |video|
      .gif.mb-5
        = link_to video_path(video) do
          = image_tag video.attachment_url, class: 'img-show mb-2 mt-2 ml-3'
        br
        = link_to 'Изменить', edit_video_path(video), class: 'ml-3'
        = link_to 'Удалить',video_path(video), class: 'ml-3', method: :delete
  = link_to 'Загрузить файл', new_video_path, class: 'btn btn-primary'

app/views/videos/new.html.slim
= render 'form'

app/views/videos/show.html.slim
.container_show
  .content.mt-5.ml-5
    = image_tag @video.attachment_url.to_s, class: 'img-show-large'
    br
    = link_to 'Изменить', edit_video_path(@video)
    = link_to 'Удалить',video_path(@video), class: 'ml-3', method: :delete